build-job:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - docker build -t my-angular-image .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push my-angular-image